declare module "*.png"
declare module "*.jpg"
declare module "*.gif"
declare module "*.mp3"
declare module "*.wav"
declare module "shade-blend-color"
declare module "react-reorder"
declare module "images-meta"